### ISSUE TITLE
get results error

### ISSUE THREAD

**Issue by safehumeng** [caojiezhang/CiaoSR#16]
modify from test.py to infer one image
```
# Copyright (c) OpenMMLab. All rights reserved.
import argparse
import os
import os.path as osp

import mmcv
import torch
from mmcv.runner import get_dist_info, init_dist, load_checkpoint

from mmedit.apis import set_random_seed
from mmedit.datasets.pipelines.loading import LoadImageFromFile
from mmedit.datasets.pipelines.normalization import RescaleToZeroOne
from mmedit.datasets.pipelines.formating import ImageToTensor
from mmedit.datasets.pipelines.generate_assistant import GenerateCoordinateAndCell
from mmedit.models import build_model

import socket
in_fbcode = True if 'fb' in socket.gethostname() or 'facebook' in socket.gethostname() else False

if in_fbcode:
    from iopath.common.file_io import PathManager
    from iopath.fb.manifold import ManifoldPathHandler

    pathmgr = PathManager()
    pathmgr.register_handler(ManifoldPathHandler())
import pdb


def parse_args():
    parser = argparse.ArgumentParser(description="mmediting tester")
    parser.add_argument("--config", default='configs/001_localimplicitsr_swinir_div2k_g1_c64b16_1000k_unfold_lec_mulwkv_res_nonlocal.py', help="test config file path")
    parser.add_argument("--checkpoint", default='./pretrain_model/swinir-ciaosr.pth', help="checkpoint file")
    parser.add_argument("--seed", type=int, default=None, help="random seed")
    parser.add_argument(
        "--deterministic",
        action="store_true",
        help="whether to set deterministic options for CUDNN backend.",
    )
    parser.add_argument("--out", default=None, help="output result pickle file")
    parser.add_argument(
        "--gpu-collect",
        action="store_true",
        help="whether to use gpu to collect results",
    )
    parser.add_argument(
        "--save_path",
        default='out',
        type=str,
        help="path to store images and if not given, will not save image",
    )
    parser.add_argument("--tmpdir", default=None, help="tmp dir for writing some results")
    parser.add_argument(
        "--launcher",
        choices=["none", "pytorch", "slurm", "mpi"],
        default="none",
        help="job launcher",
    )
    parser.add_argument("--local_rank", type=int, default=0)
    args = parser.parse_args()
    if "LOCAL_RANK" not in os.environ:
        os.environ["LOCAL_RANK"] = str(args.local_rank)
    return args


def main():
    args = parse_args()

    if "manifold" in args.config or not in_fbcode:
        print(f"load config files on ubuntu or from regu: {args.config}")
    else:
        args.config = osp.join(osp.dirname(osp.dirname(__file__)), args.config)
        print(f"load config files from fbcode with abstract path: {args.config}")
    cfg = mmcv.Config.fromfile(args.config)
    # set cudnn_benchmark
    if cfg.get("cudnn_benchmark", False):
        torch.backends.cudnn.benchmark = True
    # update CLI args according to configs (specify test checkpoint path in config)
    if args.checkpoint == "None" and cfg.get("test_checkpoint_path", None) is not None:
        args.checkpoint = cfg.test_checkpoint_path
    cfg.model.pretrained = None


    rank, _ = get_dist_info()

    # set random seeds
    if args.seed is not None:
        if rank == 0:
            print("set random seed to", args.seed)
        set_random_seed(args.seed, deterministic=args.deterministic)

    # build the dataloader
    # TODO: support multiple images per gpu (only minor changes are needed)


    # build the model and load checkpoint
    model = build_model(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)

    args.save_image = args.save_path is not None

    model.cuda()
    model.eval()

    results = {"lq_path": f"./data/2-{cfg.val_scale}.jpg"}
    pipeline = LoadImageFromFile(io_backend='disk', key='lq', flag='color', channel_order='rgb')
    results = pipeline(results)
    pipeline = RescaleToZeroOne(keys=['lq'])
    results = pipeline(results)
    pipeline = ImageToTensor(keys=['lq'])
    results = pipeline(results)
    pipeline = GenerateCoordinateAndCell(scale=cfg.val_scale)
    results = pipeline(results)
    new_results = {
        "lq": results["lq"].cuda(),
        "gt": None,
        'coord': results["coord"],
        "cell": results["cell"]
    }

    with torch.no_grad():
        result = model(
            test_mode=True,
            save_image=args.save_image,
            save_path=args.save_path,
            iteration=None,
            **new_results)


if __name__ == "__main__":
    main()

```

but get error:
```
Traceback (most recent call last):
  File "demo.py", line 130, in <module>
    main()
  File "demo.py", line 125, in main
    **new_results)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/workspace/CiaoSR/mmedited/models/restorers/basic_restorer.py", line 77, in forward
    return self.forward_test(lq, gt, **kwargs)
  File "/workspace/CiaoSR/mmedited/models/restorers/ciaosr.py", line 169, in forward_test
    pred = pred.view(*shape).permute(0, 3, 1, 2).contiguous()
RuntimeError: shape '[1, 1, 2, 3]' is invalid for input of size 26061024
```

**Comment by safehumeng** [comment]
```
 new_results = {
        "lq": results["lq"].cuda(),
        "gt": None,
        'coord': results["coord"],
        "cell": results["cell"]
    }
```
modify  to
```
 new_results = {
        "lq": results["lq"].unsqueeze(dim=0).cuda(),
        "gt": None,
        'coord': results["coord"].unsqueeze(dim=0),
        "cell": results["cell"].unsqueeze(dim=0)
    }
```
