### ISSUE TITLE
The code is not working on provided version of pytorch and mmedit

### ISSUE THREAD

**Issue by kprateek-dev** [caojiezhang/CiaoSR#6]

**Comment by caojiezhang** [comment]
What issue do you meet?

**Comment by profile838** [comment]
`CiaoSR>python tools/test.py configs/001_localimplicitsr_rdn_div2k_g1_c64b16_1000k_unfold_lec_mulwkv_res_nonlocal.py pretrain_model/rdn-ciaosr.pth
C:\Users\MiKi\miniconda3\envs\ciaosr\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
load config files on ubuntu or from regu: configs/001_localimplicitsr_rdn_div2k_g1_c64b16_1000k_unfold_lec_mulwkv_res_nonlocal.py
Traceback (most recent call last):
  File "C:\Users\MiKi\CiaoSR\tools\test.py", line 162, in <module>
    main()
  File "C:\Users\MiKi\CiaoSR\tools\test.py", line 72, in main
    cfg = mmcv.Config.fromfile(args.config)
  File "C:\Users\MiKi\miniconda3\envs\ciaosr\lib\site-packages\mmcv\utils\config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "C:\Users\MiKi\miniconda3\envs\ciaosr\lib\site-packages\mmcv\utils\config.py", line 208, in _file2dict
    mod = import_module(temp_module_name)
  File "C:\Users\MiKi\miniconda3\envs\ciaosr\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\MiKi\AppData\Local\Temp\tmpa6bwhaq8\tmpt2yieqvl.py", line 6, in <module>
ModuleNotFoundError: No module named 'mmedited'`



I carrefully read installation section, tried many times, on Windows machine and this code error got

conda env list
[https://pastebin.com/yiLgnA7m](url)

**Comment by caojiezhang** [comment]
Maybe you can specify PYTHONPATH before running python

**Comment by profile838** [comment]
could you please advice me how to do that on Windows machine?
Cause I am 100% sure that creation of environment were correct, successfully built binries....

thank you very much in advance

**Comment by zfhymx** [comment]
@zelenooki87 I'm having the same issue, can you please fix it？
